getsentry/streams

.vscode/settings.json
This might be a PR for nobody but me, but this makes VS Code's `ruff` integration work with our line length setting for `black` (so I'm not accidentally reformatting every file I touch)
=> add ruff line-length setting for VS Code

py/sentry_streams/flink/flink_adapter.py, py/sentry_streams/pipeline.py, py/tests/test_pipeline.py
The Map primitive only allows the user to provide the function to
use as a mapper via a fully qualified module name as a string.
While this is convenient and inevitable for pipeline that spans 
different code bases, it is not ergonomic for pipelines where the 
application code and the pipeline definition are in the same
code base.
Here by providing the Map function as a Callable allows for type
checking.
=> Allow the Map primitive to get a reference to a Callable

.github/workflows/build-streams.yaml, .github/workflows/release-streams.yaml, Makefile, scripts/bump-version.sh, sentry_streams/.craft.yml
Follows https://develop.sentry.dev/sdk/processes/releases/#optional-using-multiple-craft-configs-in-a-repo 
to make the repo able to release sentry-streams in the internal and external pypi.
This only releases sentry-streams so we can start importing it in other
code bases and build streaming applications without Flink in the way.
=> Add the autoamtion to release sentry-streams

platforms/flink/Dockerfile, platforms/flink/README.md, platforms/flink/docker-compose.yml, sentry_flink/sentry_flink/flink_runtime/flink_deploy.py
#31 broke the docker-based flink setup because paths in the  dockerfile were hardcoded, this fixes it
=> fix: post-split javaless flink

sentry_streams/sentry_streams/example_config.py, sentry_streams/sentry_streams/user_functions/sample_map.py
Part 1 of 2 PRs
This copies the `EventsPipelineMapFunctions` from `sample_filter.py` to a new `sample_map.py`.
The old `EventsPipelineMapFunctions` hasn't been deleted and the import paths in `sentry_flink/tests/` haven't been updated because this change will need to be deployed first. Those will be done in part 2.
=> ref: split user_functions part 1

sentry_streams/sentry_streams/pipeline/pipeline.py
This is already defined in TransformStep and Map and Filter extend those.
=> fix: Remove extra function declarations

sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/tests/test_pipeline.py
PR 1/2 of ticket https://github.com/getsentry/streams/issues/40?issue=getsentry%7Cstreams%7C43
the function `get_function` is copy pasted from https://github.com/getsentry/streams/blob/65f71d4e46a6eff24f5e331e6e09b14ab8401877/sentry_flink/sentry_flink/flink/flink_adapter.py#L57-L78, did not edit logic
After this is merged, I will create a new release of sentry_streams, then remove the function from flink_adapter file linked above
=> ref(sentry_streams): add function to TransformStep class

sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/stream_adapter.py, sentry_streams/sentry_streams/examples/alerts.py, sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/examples/billing.py, sentry_streams/sentry_streams/examples/spans_buffer.py, sentry_streams/sentry_streams/examples/word_counter.py, sentry_streams/sentry_streams/pipeline/pipeline.py
Some refactoring to Batch and FlatMap primitives. 
Removed the Unbatch primitive, as I don't think it should be a primitive that is independent from FlatMap. There is not much that an Unbatch primitive abstracts away. In fact, even if we exposed an Unbatch, a user would still need to know the format of data flowing through the pipeline: an Unbatch cannot be plugged in "anywhere" in a pipeline. This same argument doesn't apply to Batch, because it _does_ actually abstract away some details and _can_ technically be used as an independent building block anywhere in the pipeline. 
I think this makes the usability of the API better, and actually reduces the cognitive overhead of using it. As a side effect, the typing is also clearer.
=> ref: Remove Unbatch, flesh out Reduce ABC

README.md, sentry_flink/README.md, sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/loader.py, sentry_streams/sentry_streams/adapters/stream_adapter.py, sentry_streams/sentry_streams/dummy/dummy_adapter.py, sentry_streams/sentry_streams/examples/transfomer.py, sentry_streams/sentry_streams/runner.py, sentry_streams/tests/adapters/arroyo/test_adapter.py
The arroyo adapter was not wired onto the runner so we could not 
actually run Arroyo consumers. This wires it up together.
Specifically:
- the loader can instantiate an Arroyo adapter now. 
There are types to fix but that requires a larger change.
- Initialized the logger with a reasonable format and replaced
some print with log statements
- Added a signal handler on the runner 
- Fixed the readme by adding a quickstart section
=> Adapte the runner to run the Arroyo adapter

sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/arroyo/steps.py, sentry_streams/sentry_streams/examples/alerts.py, sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/examples/billing.py, sentry_streams/sentry_streams/examples/blq.py, sentry_streams/sentry_streams/examples/broadcast.py, sentry_streams/sentry_streams/examples/spans_buffer.py, sentry_streams/sentry_streams/examples/transfomer.py, sentry_streams/sentry_streams/examples/word_counter.py, sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/tests/adapters/arroyo/conftest.py, sentry_streams/tests/adapters/arroyo/test_adapter.py, sentry_streams/tests/adapters/arroyo/test_consumer.py, sentry_streams/tests/adapters/arroyo/test_steps.py, sentry_streams/tests/test_pipeline.py, sentry_streams/tests/test_runner.py
Our goal is to provide an abstraction over streams. 
We are hiding all the aspects of Kafka like message, commit policy, partitions etc.
Why having to call a stream source KafkaSource when the user only needs to care of a sterm of events ?
=> Make streams less Kafkaesque

sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/stream_adapter.py, sentry_streams/sentry_streams/runner.py
https://github.com/getsentry/streams/pull/79 caused a name clash with the `StreamSink` generic, this renames the generic types to `StreamT`/`StreamSinkT`
I'll open another PR to fix the imports for the flink adapter
=> fix: rename Stream/StreamSink generics

README.md, sentry_flink/sentry_flink/flink/flink_adapter.py, sentry_flink/tests/test_pipeline.py, sentry_streams/sentry_streams/examples/alerts.py, sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/examples/billing.py, sentry_streams/sentry_streams/examples/blq.py, sentry_streams/sentry_streams/examples/broadcast.py, sentry_streams/sentry_streams/examples/spans_buffer.py, sentry_streams/sentry_streams/examples/word_counter.py, sentry_streams/sentry_streams/runner.py, sentry_streams/tests/adapters/arroyo/conftest.py, sentry_streams/tests/adapters/arroyo/test_adapter.py, sentry_streams/tests/adapters/arroyo/test_consumer.py, sentry_streams/tests/test_pipeline.py
Our current way of configuring topics in `runnner.py` allows topics to be aliased to different  names, but the arroyo adapter has no knowledge of the topics config and doesn't work with aliased topics.
We'll reach a decision on this in the future, but for now keep our current structure but remove all the `logical-events` aliases for the `events` topic.
=> ref: remove topics mapping from env config

sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/examples/blq.py, sentry_streams/sentry_streams/examples/transfomer.py, sentry_streams/sentry_streams/pipeline/__init__.py, sentry_streams/sentry_streams/pipeline/chain.py, sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/tests/pipeline/test_chain.py, sentry_streams/tests/test_pipeline.py, sentry_streams/uv.lock
The team discussed multiple options on how to represent pipelines in the python DSL.
The winning option was to use a Flink like chaining syntax that has a few advantages:
- It makes the topology evident as each step is chained to the previous one as a
function call on the return value of the previous one.
- It makes routing and broadcasting much easier.
This PR introduces the DSL and supports all the existing primitives.
Please see the example to see how the syntax looks like.
The transition will be done in three stages:
- This one introduces the new DSL as a way to produce the existing pipeline data structure.
The chained DSL would introduce fundamental changes to the translator. It becomes
easier. But I cannto change that as well in this PR
- Port all the examples. I ported two here.
- …
=> Introduce chained primitives to replace the old DSL

sentry_streams/sentry_streams/examples/multi_chain.py, sentry_streams/sentry_streams/pipeline/__init__.py, sentry_streams/sentry_streams/pipeline/chain.py, sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/sentry_streams/runner.py, sentry_streams/tests/test_pipeline.py
A streaming pipeline can cinlude multiple Chains each of which
starts with a different consumer.
This is how we can manage pipelines that have intermediate topics.
This supports the creation of a pipeline with the DSL when there
are multiple sources.
See the example for details on how it works
=> Add support for multiple chains in the DSL

sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/stream_adapter.py, sentry_streams/sentry_streams/dummy/dummy_adapter.py, sentry_streams/sentry_streams/examples/blq.py, sentry_streams/sentry_streams/pipeline/chain.py, sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/sentry_streams/runner.py, sentry_streams/tests/pipeline/test_chain.py, sentry_streams/tests/test_pipeline.py, sentry_streams/tests/test_runner.py
Broadcast in flink doesn't require any processing as it works implicitly by just plugging a step into the `inputs` of mutliple downstream steps.
Broadcast in arroyo will need to do actual work on the adapter side, so we'll need an explicit `Broadcast()` step for that to work properly. This PR adds that step to the pipeline graph.
The `Broadcast()` step also has a routes list in the form of a list of `Branch()` much like the router step does.
=> feat: add explicit Broadcast step to pipeline graph

sentry_streams/pyproject.toml, sentry_streams/sentry_streams/deployment_config/test_flink_config.yaml, sentry_streams/sentry_streams/runner.py
Small change so we can remove any hardcoded configurations from tests
=> ref: Make Flink tests also use deployment config

sentry_streams/docs/source/intro.rst, sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/deployment_config/blq_config.yaml, sentry_streams/sentry_streams/deployment_config/test_flink_config.yaml, sentry_streams/sentry_streams/deployment_config/transformer_config.yaml, sentry_streams/sentry_streams/examples/blq.py, sentry_streams/uv.lock
The arroyo adapter didn't work with the new deployment config, this PR should fix.
Also includes config file for `blq.py` example.
The `flink_deploy` script will also need to be updated for the deployment config to work on local dockerized flink, that will come in a future PR.
=> fix: arroyo adapter deployment config

sentry_streams/sentry_streams/config_types.py
Update to a `Sequence[str]` to match the correct type
=> fix: Update config types for bootstrap_servers

.pre-commit-config.yaml, sentry_streams/pyproject.toml, sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/arroyo/broadcaster.py, sentry_streams/sentry_streams/adapters/arroyo/consumer.py, sentry_streams/sentry_streams/adapters/arroyo/forwarder.py, sentry_streams/sentry_streams/adapters/arroyo/msg_wrapper.py, sentry_streams/sentry_streams/adapters/arroyo/reduce.py, sentry_streams/sentry_streams/adapters/arroyo/routes.py, sentry_streams/sentry_streams/adapters/arroyo/steps.py, sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/examples/blq.py, sentry_streams/sentry_streams/examples/blq_fn.py, sentry_streams/sentry_streams/examples/multi_chain.py, sentry_streams/sentry_streams/examples/transformer.py, sentry_streams/sentry_streams/pipeline/batch.py, sentry_streams/sentry_streams/pipeline/chain.py, sentry_streams/sentry_streams/pipeline/message.py, sentry_streams/sentry_streams/pipeline/msg_parser.py, sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/tests/adapters/arroyo/conftest.py, sentry_streams/tests/adapters/arroyo/test_adapter.py, sentry_streams/tests/adapters/arroyo/test_broadcaster.py, sentry_streams/tests/adapters/arroyo/test_consumer.py, sentry_streams/tests/adapters/arroyo/test_forwarder.py, sentry_streams/tests/adapters/arroyo/test_steps.py, sentry_streams/tests/pipeline/test_chain.py, sentry_streams/tests/test_runner.py, sentry_streams/uv.lock
Does the following:
- Links types of different steps of an ExtensibleChain
- Provides a simple Message class to carry message metadata through the pipeline. This allows for decoupling certain steps, like parsing/deserialization from the stream source step. 
- Basic message decoders/encoders provided out of the box in the API (JSON, protobuf)
- Basic header filtering in the source
- Schema validation and transforming raw bytes into a schema-enforced message type
- General type checks
- Unit tests cleanup
Still to do:
- Improve a bunch of naming (of interfaces, of files, etc.)
- Provide full support for Protobuf
=> ref: Type out chains and steps

sentry_streams/README.md
When I tried to publish this package built by maturin I get this error from 
pypi:
```
wine: 25hWARNING  Error during upload. Retry with the --verbose option for more details. 
twine: ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
twine:          The description failed to render for 'text/markdown; charset=UTF-8;    
twine:          variant=GFM'. See https://pypi.org/help/#description-content-type for  
twine:          more information.                                                      
twine: 
```
It seems the difference between maturin and setuptools is the readme content encoding.
setuptools:
`Description-Content-Type: text/markdown` 
maturin
`text/markdown; charset=UTF-8; variant=GFM`
which apaprently makes pypi unhappy if the readme is empty. …
=> Add some content to the readme

sentry_streams/sentry_streams/runner.py
i think for the near future only `arroyo` and `rust_arroyo` adapters will be used
=> ref(runner): add choices list 

.github/workflows/build-streams.yaml, .github/workflows/rust-ci.yaml, sentry_streams/Cargo.toml
Since people interact with cargo directly in local development, i'd argue for the sake of ergonomics that the features should default to what is needed in local development. For the release job we can have a longer list of arguments. Going to run the build-streams job as well in CI, because it'd suck if any breakage is only revealed during release.
=> ref(ci): Disable extension-module by default

sentry_streams/sentry_streams/adapters/arroyo/adapter.py, sentry_streams/sentry_streams/adapters/arroyo/broadcaster.py, sentry_streams/sentry_streams/adapters/arroyo/consumer.py, sentry_streams/sentry_streams/adapters/arroyo/msg_wrapper.py, sentry_streams/sentry_streams/adapters/arroyo/rust_arroyo.py, sentry_streams/sentry_streams/adapters/arroyo/steps.py, sentry_streams/sentry_streams/examples/simple_map_filter.py, sentry_streams/sentry_streams/pipeline/__init__.py, sentry_streams/sentry_streams/pipeline/message.py, sentry_streams/sentry_streams/pipeline/msg_parser.py, sentry_streams/sentry_streams/rust_streams.pyi, sentry_streams/src/lib.rs, sentry_streams/src/messages.rs, sentry_streams/tests/adapters/arroyo/test_broadcaster.py, sentry_streams/tests/adapters/arroyo/test_consumer.py, sentry_streams/tests/adapters/arroyo/test_delegate.py, sentry_streams/tests/adapters/arroyo/test_forwarder.py, sentry_streams/tests/adapters/arroyo/test_steps.py
This is the foundation of the work to manage Message structures in Rust.
There is a more refactoring  work to do to have a proper Rust Message abstraciton
though this is step one we can build on top of.
We are trying to move more streaming processing logic to Rust (for efficiency).
At the same time, we want to build Python streaming application,
Rust streaming application and hybrid streaming application where some
steps are in Python and some are in Rust.
The requirement above imply both Rust and Python must understand the Message
data structure, thus this has to be defined in Rust and exposed via Pyo3.
Rust orchestrate the pipeline. As such it will create the message instance
after the consumer. 
Having both Rust and Python streaming steps means we need multiple types of
messages (we …
=> Move the Message data structure to Rust

sentry_streams/sentry_streams/adapters/arroyo/reduce_delegate.py, sentry_streams/sentry_streams/adapters/arroyo/rust_arroyo.py, sentry_streams/sentry_streams/adapters/arroyo/rust_step.py, sentry_streams/sentry_streams/examples/simple_batching.py, sentry_streams/sentry_streams/pipeline/message.py, sentry_streams/src/messages.rs, sentry_streams/tests/adapters/arroyo/test_reduce_delegate.py
Based on https://github.com/getsentry/streams/pull/118
This uses the `RustOperatorDelegate` to make the Python Reduce step
working on the Rust Adapter.
We create the reduce step as an Arroyo Python strategy just like in the
Python adapter. Then we wire an `OutputRetriever` as following step.
This is used to colelct the result.
The above is then wrapped into the `ReduceDelegate` which extends
`RustOperatorDelegate`, which is thus manageable by the Rust runtime.
=> Support Reduce in the Rust Adapter as a Python delegate

scripts/bump-version.sh, sentry_streams/uv.lock
The release process started bumping the version number in uv.lock in https://github.com/getsentry/streams/pull/114.
The problem is that the bump version script is now changing the version of all dependencies making the release process fail.
https://github.com/getsentry/streams/compare/main...release-sentry-streams/0.0.19#diff-8ec0ade2e1fdb159015a5e3a837db7a165b0f563b0cf447a82e54e191f57e828R6
Reverting that change so we can release.
=> Avoid bumping version number in uv.lock during release

sentry_streams/sentry_streams/adapters/arroyo/reduce_delegate.py, sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/examples/transformer.py, sentry_streams/sentry_streams/pipeline/batch.py, sentry_streams/sentry_streams/pipeline/chain.py, sentry_streams/sentry_streams/pipeline/pipeline.py, sentry_streams/tests/adapters/arroyo/test_reduce_delegate.py, sentry_streams/uv.lock
A really simple way to unblock the work where a batching step happens before parsing. I can also introduce the concept of `Schema` in this PR, where we have an enum of all the allowed schemas / topic names. 
We should not stick with this in the long term, and likely enforce all Accumulators/Reduce steps to output a `Tuple[MutableSequence[InputType], Schema]`. Making this is a more significant typing change as it involves making sure primitives like `FlatMap` are also able to handle that output type.
=> quick-fix: Ensure schema is retained after a batching step

.pre-commit-config.yaml
This PR adds `rustup fmt` to run as a part of our pre-commit.
I ripped this from the arroyo repo pre-commit config: https://github.com/getsentry/arroyo/blob/main/.pre-commit-config.yaml#L35-L43
=> add cargo fmt to precommit

sentry_streams/sentry_streams/examples/batching.py, sentry_streams/sentry_streams/pipeline/chain.py, sentry_streams/sentry_streams/pipeline/msg_codecs.py, sentry_streams/tests/pipeline/test_msg_codecs.py
this `BatchParser` is to be used after a `Batch` step, not to be confused with the `Parser` step which is to be used before a `Batch` step.
also updated the example in `Batching.py` to use this `BatchParser`, tested successfully locally
=> feat(chain): add BatchParser

sentry_streams/sentry_streams/adapters/arroyo/rust_arroyo.py, sentry_streams/sentry_streams/deployment_config/simple_map_filter.yaml, sentry_streams/sentry_streams/examples/simple_map_filter.py
Addresses https://github.com/getsentry/streaming-planning/issues/182. GCS Sink takes 2 configuration parameters
- bucket name (is static)
- object file names (can be dynamically generated)
This PR adds support for handling any overrides that may be provided in the config file for a specific pipeline. The rule of thumb is that any params defined in the config file will override any params as defined in the pipeline.
=> ref: Handle overrides in GCSSink from config

sentry_streams/src/callers.rs, sentry_streams/src/filter_step.rs, sentry_streams/src/messages.rs, sentry_streams/src/python_operator.rs, sentry_streams/src/routers.rs, sentry_streams/src/test_operators.rs, sentry_streams/src/transformer.rs
- Unify rust → python facilities in `transform`, `route` and `filter` with `try_apply_py`. When calling into python with `try_apply_py` the return value will be `Result<T, ApplyError>`, where `ApplyError` can be either `InvalidMessage`, which is meant to signal to the event loop to not retry the message, or `ApplyFailed`, which indicates some ordinary errors. `try_apply_py` also handles logging python stack traces in event of an error.
- Add conversion for `ApplyError::InvalidMessage` → Arroyo runtime's `MessageRejected`
- Implements `Into` traits for `PyStreamingMessage` → `Py<PyAny>`, since we're doing the `match` + `clone_ref` over and over again.
=> ref(rust): Parse and handle errors when interfacing with python code in route and filter

sentry_streams/src/callers.rs, sentry_streams/src/filter_step.rs, sentry_streams/src/routers.rs, sentry_streams/src/transformer.rs
These tests are failing on main for @evanh and myself saying its not able to find `sentry-kafka-schemas` despite the package being in our venv.
Marking them as ignored until we get our devenv sorted out.
=> temp: ignore failing tests

sentry_streams/docs/source/runtime/arroyo.rst
This PR adds some docs on our arroyo runtimes, with a focus on routes and watermarks.
=> feat(docs): add some Arroyo runtime docs

sentry_streams/src/python_operator.rs
In python adapter, we are casting the class name of the exception into a string in order to perform type checking. This method is not precise and prone to undesired behaviours as any exception with the same name will be considered the correct type.
This PR uses the pyo3 `import_exception` macro to get the actual exception from arroyo and use the python interpreters isinstance function to check types.
=> ref(rust): Use python for instance check when parsing error in PythonAdapter

sentry_streams/src/broadcaster.rs, sentry_streams/src/callers.rs, sentry_streams/src/committable.rs, sentry_streams/src/filter_step.rs, sentry_streams/src/messages.rs, sentry_streams/src/python_operator.rs, sentry_streams/src/routers.rs
After #158 we should only be using `initialize_python()` for all tests as that uses the correct python for tests
=> fix: replace freedthreaded_python with initialize_python everywhere

sentry_streams/sentry_streams/adapters/arroyo/rust_arroyo.py, sentry_streams/sentry_streams/rust_streams.pyi
adds the `thread_count` arg to GCSSink without doing anything with it. This PR simply wires it up so that when https://linear.app/getsentry/issue/STREAM-338/support-multiple-concurrencyconfig-object-in-rust this ticket is done `GCSSink` can start using it
=> expose thread_count to GCSSink

scripts/flink-jar-download.sh, sentry_flink/pyproject.toml, sentry_flink/sentry_flink/flink/flink_adapter.py, sentry_flink/tests/test_pipeline.py, sentry_flink/uv.lock
Addresses security vulnerability in protobuf 4.23.4 imported by Beam which is imported by Flink.
This was not in any production code.
https://linear.app/getsentry/issue/STREAM-298/protobuf-vulnerability-in-getsentrystreams
=> Bump Flink to use a more recent protobuf

sentry_streams/sentry_streams/adapters/arroyo/reduce.py, sentry_streams/tests/adapters/arroyo/test_reduce.py
This PR updates `test_submit_and_poll` in test_reduce to check that the committable received when closing a sliding window is the correct one (i.e. only the committable of messages in the accumulator that's being closed)
=> fix(reduce): test that the right committable is submitted

sentry_streams/sentry_streams/adapters/arroyo/rust_step.py
followup to [PR ](https://github.com/getsentry/streams/pull/203), the submit function needs a more specific return type, because the caller in pyo3 in rust needs a list
=> fix(watermark): add specific func signature

sentry_streams/pyproject.toml, sentry_streams/uv.lock
sbc uses 8.1.8 and snuba uses 8.1.7, sentry uses 8.2.1
=> downgrade click
